{{- $gpuCount := .Values.gpuCount -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "tensorflow-serving.fullname" . }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: {{ template "tensorflow-serving.chart" . }}
    app: {{ template "tensorflow-serving.name" . }}
  annotations:
    "helm.sh/created": {{ .Release.Time.Seconds | quote }}
spec:
  replicas: {{ .Values.replicas }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      release: {{ .Release.Name | quote }}
      app: {{ template "tensorflow-serving.name" . }} 
  template:
    metadata:
      labels:
        heritage: {{ .Release.Service | quote }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "tensorflow-serving.chart" . }}
        app: {{ template "tensorflow-serving.name" . }}
    spec:
      containers:
        - name: serving
          image: "{{ .Values.image }}"
          imagePullPolicy: "{{ .Values.imagePullPolicy }}"
          command:
            - "/usr/bin/tensorflow_model_server"
          args:
            - "--port={{ .Values.port }}"
            - "--model_name={{ .Values.modelName }}"
            - "--model_base_path={{ .Values.modelPath }}"
            {{- if .Values.modelConfigFile }}
            - "--model_config_file={{ .Values.modelConfigFile }}"
            {{- end }}
          ports:
            - containerPort: {{ .Values.port }}
              name: serving
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: serving
            initialDelaySeconds: 15
            timeoutSeconds: 1
          resources:
            requests:
              cpu: {{ .Values.cpu }}
              memory: {{ .Values.cpu }}
              nvidia.com/gpu: {{ .Values.cpu }}
          volumeMounts:
          {{- if .Values.mountPath }}
            - mountPath: {{ .Values.mountPath }}
          {{- else }}
            - mountPath: /data
          {{- end }}
              name: model-volume
      volumes:
        - name: model-volume
      {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
              claimName: {{ .Values.persistence.existingClaim | default (include "tensorflow-serving.fullname" .) }}
      {{- else }}
          emptyDir: {}
      {{- end }}
